name: Github Action 테스트 1번.
on:
  push:
    branches:
      - main
jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World 출력
        run: echo "Hello, World"
      - name: 여러개 명령어 추가하기
        run: |
          echo "첫 번째 명령어"
          echo "두 번째 명령어"
          echo "세 번째 명령어"
      - name: Github Actions 내장 변수 사용
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY